export default
[
  { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101" },
  { "_id": "A102", "title": "Combustion Analysis", "course": "RS101" },
  { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101" },
  { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" },
  { "_id": "A202", "title": "Flow Analysis", "course": "RS102" },
  { "_id": "A203", "title": "Heating Analysis", "course": "RS102" },
  { "_id": "A301", "title": "Structural Design Task", "course": "RS103" },
  { "_id": "A302", "title": "Orbital Calculations", "course": "RS103" },
  { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103" },
  { "_id": "A401", "title": "Exoplanet Detection Techniques", "course": "RS104" },
  { "_id": "A402", "title": "Astrobiology Research Paper", "course": "RS104" },
  { "_id": "A403", "title": "Propulsion Technology Analysis", "course": "RS104" },
  { "_id": "A501", "title": "Space Weather Impact Report", "course": "RS105" },
  { "_id": "A502", "title": "Observational Astronomy Project", "course": "RS105" },
  { "_id": "A503", "title": "Space Colonization Debate", "course": "RS105" },
  { "_id": "A601", "title": "CubeSat Design Project", "course": "RS106" },
  { "_id": "A602", "title": "Quantum Communications Essay", "course": "RS106" },
  { "_id": "A603", "title": "AI in Space Exploration Presentation", "course": "RS106" },
  { "_id": "A701", "title": "Space Elevator Concept Design", "course": "RS107" },
  { "_id": "A702", "title": "Terraforming Mars Proposal", "course": "RS107" },
  { "_id": "A703", "title": "Dyson Sphere Feasibility Study", "course": "RS107" },
  { "_id": "A801", "title": "Dark Matter Research Assignment", "course": "RS108" },
  { "_id": "A802", "title": "Multiverse Theory Essay", "course": "RS108" },
  { "_id": "A803", "title": "Time Travel Theoretical Model", "course": "RS108" },
  { "_id": "A901", "title": "Space Debris Cleanup Proposal", "course": "RS109" },
  { "_id": "A902", "title": "SETI Signal Analysis Simulation", "course": "RS109" },
  { "_id": "A903", "title": "Next-Gen Space Suit Design", "course": "RS109" }

];